### ISSUE TITLE
Login Example

### ISSUE THREAD

**Issue by alrightsure** [butttons/supabase-auth-helpers#1]
Hello! Thank you for making this package; it's good to see I'm not the only one that has this gripe with Supabase's auth implementation.

Are you able to provide an example of how you're setting the cookie used by this package? It seems the cookie set when using the @supabase/ssr package is not what the library is expecting. I get the following error when using the ssr package to login and attempting to validate:
`{
  error:  [SupabaseAuthError: Invalid auth cookie] {
  code: 'INVALID_COOKIE',
  name: 'SupabaseAuthError'
}`

Thanks!

**Comment by butttons** [comment]
Ah, thanks. I should update the docs to reflect what kind of client setup is needed. 

Anyway, this package assumes that you've done your authentication with the PKCE flow - https://supabase.com/docs/guides/auth/sessions/pkce-flow

How is your client side setup looking like?

I was thinking of adding another override to the `getUser` method that will also accept `Headers`, in case people are using the `Authorization: Bearer ${session.access_token}` strategy in case of implicit flows.

**Comment by alrightsure** [comment]
I just pushed to this repo here: https://github.com/alrightsure/supabase-authhelpers-test

I have the ssr package setup to use the PKCE flow, but I still seem to be getting an invalid cookie error.

**Comment by butttons** [comment]
Also, it turns out I am using a very old version of the ssr package. 

Can you inspect your cookies in the requests to your backend? Do they contain a cookie named "sb-{SUPABASE_ID}-auth-token"?

**Comment by butttons** [comment]
Okay, so it's my fault for not checking the version I was on. So, the latest version seems to base64 encode the cookie contents. I'll update this package accordingly. Hopefully, in a few days :pray: 

<img width="167" alt="image" src="https://github.com/user-attachments/assets/bf827027-0ff8-4dba-b4cc-363cd84aa2fe">

**Comment by alrightsure** [comment]
Awesome! I do see the cookie is still called sb-{SUPABASE_ID}-auth-token in the latest version too.

**Comment by butttons** [comment]
Hey, I've made some changes. Check out the latest version.

**Comment by alrightsure** [comment]
Awesome! Looks like it's working. So excited to be able to use Supabase auth without the performance hit!
